# Generated by Django 5.2.17 on 2026-09-25 04:46

import django.contrib.auth.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cart', '0002_cart_actual_price_cart_discount_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], db_index=True, max_length=10)),
                ('external_payment_id', models.CharField(max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='discount_code',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price_paid',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='cart',
            name='locked_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('locked', 'Locked'), ('ordered', 'Ordered')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='locked_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('fulfilled', 'Fulfilled'), ('payment_pending', 'PaymentPending'), ('refunded', 'Refunded'), ('paid', 'Paid')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order'),
        ),
        migrations.CreateModel(
            name='DiscountCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('perc', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=6)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_discount_code_name')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cart.user'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='cart.user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cart.user'),
        ),
    ]
